# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [49]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [50]:
import numpy as np
import math

#### 2. Print the numpy version and the configuration (★☆☆)

In [51]:
print(np.__version__)

1.24.3


#### 3. Create a null vector of size 10 (★☆☆)

In [52]:
v1 = np.zeros(10)
print(v1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [53]:
print(v1.size)
print(v1.nbytes)

10
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [54]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [55]:
v1 = np.zeros(10)
v1[4] = 1
print(v1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [56]:
v1 = np.arange(10, 50)
print(v1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [57]:
for i in range(int(len(v1) / 2)):
    tmp = v1[i]
    v1[i] = v1[len(v1) - 1 - i]
    v1[len(v1) - 1 - i] = tmp
print(v1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [58]:
mat1 = np.arange(0, 9).reshape(3, 3)
print(mat1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [59]:
v1 = np.array([1,2,0,0,4,0])
res=[]
for i in range(len(v1)):
    if v1[i] == 0:
        res.append(i)
print(res)

[2, 3, 5]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [60]:
id1 = np.eye(3)
print(id1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [61]:
v2 = np.random.randn(27).reshape(3, 3, 3)
print(v2)

[[[-0.29632975 -0.21211043  1.07187109]
  [-0.03055549  0.57190758 -0.21780286]
  [-1.03998054  0.63283016  1.77553807]]

 [[ 1.88534922 -0.99708996  2.04404679]
  [ 0.43839362  1.27498624 -1.25789922]
  [-1.50510212 -0.34893486 -0.31034905]]

 [[ 0.06207029 -3.16223228  1.31571452]
  [ 1.99631293 -1.59995603 -0.83418707]
  [-0.67680182 -0.0411801  -0.56459087]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [62]:
v1 = np.random.rand(100).reshape(10, 10)
maxNum = v1.max()
minNum = v1.min()
print("[+] MaxNum: ", maxNum, " MinNum: ", minNum)

[+] MaxNum:  0.9914993819856742  MinNum:  0.004882342511680071


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [63]:
meanVal = np.random.rand(30).mean()
print(meanVal)

0.5327536139150373


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [64]:
mat1 = np.arange(0, 25).reshape(5, 5)
l1, l2 = 0, len(mat1[0]) - 1
w1, w2 = 0, len(mat1) - 1


for l in range(l1, l2 + 1):
    mat1[w1][l] = 1
for w in range(w1, w2 + 1):
    mat1[w][l2] = 1
for l in range(l2, l1 - 1, -1):
    mat1[w2][l] = 1
for w in range(w2, w1 - 1, -1):
    mat1[w][l1] = 1

print(mat1)

[[ 1  1  1  1  1]
 [ 1  6  7  8  1]
 [ 1 11 12 13  1]
 [ 1 16 17 18  1]
 [ 1  1  1  1  1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [65]:
mat1 = np.arange(1, 10).reshape(3, 3)
print(mat1, end='\n\n')

mat1 = np.pad(mat1, ((2, 3), (1, 0)), mode='constant', constant_values= 0)
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0 0 0 0]
 [0 0 0 0]
 [0 1 2 3]
 [0 4 5 6]
 [0 7 8 9]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [66]:
v1 = np.nan
print(type(v1))
print(type(np.nan))

# NaN (Not a Number) represents an undefined or unrepresentable value in floating-point arithmetic.
# It's not equal to any other value, including itself.

# The == operator performs value comparison.
# NaN (Not a Number) is defined as not equal to any v

# The "is" operator performs identity comparison.
# It checks if two objects refer to the exact same memory location.

# In many Python implementations, np.nan is often a singleton object, 
# meaning there's only one instance of it in memory.

if v1 == v1:
    print("Yes")

if np.nan == np.nan:
    print("Yes")

if np.nan is np.nan:
    print("Yes")

if np.isnan(v1):
    print("Yes")


<class 'float'>
<class 'float'>
Yes
Yes


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [67]:
mat1 = np.zeros(25).reshape(5, 5)
count = 0

for i in range (len(mat1)):
    for j in range(len(mat1[0])):
        if (i > j):
            mat1[i][j] = count
            count += 1
print(mat1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 2. 0. 0. 0.]
 [3. 4. 5. 0. 0.]
 [6. 7. 8. 9. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [68]:
mat1 = np.zeros(64).reshape(8, 8)
count = 1

for i in range(len(mat1)):
    if (count % 2 == 0):
        count = 1
    else:
        count = 0
    for j in range(len(mat1[0])):
        if (count % 2 == 0):
            mat1[i][j] = 0
        else:
            mat1[i][j] = 1
        count += 1

print(mat1)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [69]:
# index would be (1,5,3)
v2 = np.arange(11, 347).reshape(6, 7, 8)
print(v2[1][5][3])

# Using unravel_index
flatIndx = 99 #(c-style indexing so 100th element is at flat_index:99)
idx = np.unravel_index(flatIndx, (6, 7, 8))
print(idx)

110
(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [70]:
v1 = np.arange(1, 5).reshape(2, 2)
print(v1, end='\n\n')

v1 = np.tile(v1, ((3, 1))) # 3 times niche and 1 time side mei
print(v1)

[[1 2]
 [3 4]]

[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [71]:
if np.sqrt(-1) == np.emath.sqrt(-1): # nan != j
    print("Yes")
else:
    print("No")

No


/var/folders/2v/33p_wnzd3gj0lfp0r82qrhl00000gp/T/ipykernel_5378/1652928068.py:1: RuntimeWarning: invalid value encountered in sqrt
  if np.sqrt(-1) == np.emath.sqrt(-1): # nan != j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [72]:
yesterday = np.datetime64('today') - np.timedelta64(1,'D')
today = np.datetime64('today')
tomorrow = np.datetime64('today') - np.timedelta64(1, 'D')
yesterday

numpy.datetime64('2024-02-05')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [73]:
startDate = np.datetime64('2016-07-01')
endDate = np.datetime64('2016-08-01')
np.arange(startDate, endDate, dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [74]:
a = np.ones(3)
b = np.ones(3)
((a + b) * (-a/2))

array([-1., -1., -1.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [75]:
arr = np.random.uniform(low=0, high=100, size=10)
print(arr)

a1 = np.floor(arr)
a2 = arr.astype(int)

print(a1)
print(a2)

[ 6.79747881 25.32076071  8.69987931  5.43308292 94.12210957 38.09046032
 26.87692274 73.78892712 13.49824233  2.86090671]
[ 6. 25.  8.  5. 94. 38. 26. 73. 13.  2.]
[ 6 25  8  5 94 38 26 73 13  2]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [76]:
arr = np.zeros((5, 5))
addArr = np.arange(5)
arr + addArr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [77]:
np.random.randint(low=0, high=10, size=10)

array([2, 7, 6, 1, 1, 2, 0, 4, 6, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

np.linspace(0, 1, 11)[1:]

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [78]:
arr = np.sort(np.random.rand(10))
arr

array([0.3848021 , 0.53678501, 0.58705219, 0.64376414, 0.72873427,
       0.81342419, 0.83537676, 0.83836725, 0.90199215, 0.99143071])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [79]:
sum(np.arange(1, 11))

TypeError: 'int' object is not callable

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
a = np.random.rand(5)
b = np.random.rand(5)

np.array_equal(a, b)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
# true immutability isn't directly achievable like it is with Python strings or tuples. However, you
# can employ several techniques to effectively restrict or prevent modifications and achieve a state
# close to immutability

arr = np.arange(5)
arr.flags.writeable = False

try:
    arr[0] = 1
except ValueError:
    print("Array is read-only")

Array is read-only


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
arr = np.arange(1, 6)
new_arr = np.array([])

for i in range(len(arr)):
    new_arr= np.concatenate((new_arr[:4 * i], [0,0,0,i + 1], new_arr[4 * i:]))
    print(new_arr)

[0. 0. 0. 1.]
[0. 0. 0. 1. 0. 0. 0. 2.]
[0. 0. 0. 1. 0. 0. 0. 2. 0. 0. 0. 3.]
[0. 0. 0. 1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4.]
[0. 0. 0. 1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
arr1 = np.random.rand(75).reshape(5, 5, 3)
arr2 = np.arange(25).reshape(5, 5, 1)

arr1 * arr2 # element-wise multiplication

array([[[ 0.        ,  0.        ,  0.        ],
        [ 0.39906688,  0.17568847,  0.62081193],
        [ 0.51773775,  1.76656879,  0.72637404],
        [ 2.55292319,  1.81777889,  1.64799424],
        [ 1.89119455,  2.01770632,  0.27257904]],

       [[ 4.98356944,  1.53054179,  4.44450611],
        [ 5.63359387,  3.85118714,  5.56548343],
        [ 4.83349039,  1.66345808,  0.29794363],
        [ 5.90518872,  6.24794938,  1.84415203],
        [ 2.69611312,  2.76615163,  8.30127106]],

       [[ 1.81047068,  6.46820952,  3.5118618 ],
        [10.09429096, 10.68364459,  6.76248233],
        [ 5.8433416 ,  3.7917874 ,  6.19494826],
        [ 5.59053999,  8.3622123 , 12.74283316],
        [ 1.09979011,  0.83279221,  5.12379855]],

       [[13.73946561,  3.99185262, 14.70266713],
        [ 2.06737985,  2.72460179,  8.96374594],
        [ 0.04898867, 10.62832959, 12.80981066],
        [17.53142751,  9.99141218,  6.85959454],
        [13.32739772,  0.80782936, 16.69096372]],

       [[18.

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
arr = np.arange(9).reshape(3, 3)
tmp = arr[0].copy()
arr[0] = arr[1]
arr[1] = tmp
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
c = [1,3,4,4]
a = []

for i in range(len(c)):
    for j in range(c[i]):
        a.append(i)
a

[0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
window_size = 3
arr = [1,3,4,5,7,11,13,12,12]
movingAvg = []

for i in range(len(arr) - window_size + 1):
    sum = 0
    for j in range(i, i + window_size):
        sum += arr[j]
    movingAvg.append(sum / window_size)
movingAvg

[2.6666666666666665,
 4.0,
 5.333333333333333,
 7.666666666666667,
 10.333333333333334,
 12.0,
 12.333333333333334]

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
z = [1,2,3,4,5,6,7,8,9]
arr = []

for i in range(0, len(z) - 3 + 1, 3):
    arr.append([z[i], z[i + 1], z[i + 2]])
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
boolVar = True
boolVar = not boolVar

floatVal = 5.04
floatVal *= -1

print("[+] Boolean: ", boolVar, " floatVal: ", floatVal)

[+] Boolean:  False  floatVal:  -5.04


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def calcDist(l1, l2, pt):
    a = l2[1] - l1[1]
    b = l2[0] - l1[0]
    c = l2[0] * l1[1] - l1[0] * l2[1]

    dist = abs(a * pt[0] + b * pt[1] + c) / math.sqrt(a**2 + b**2)
    return dist

In [ ]:
p0 = [[0,0], [5,10], [2,2]]
p1 = [[1,2], [8,13], [7,4]]
pt = [5, 7]

# Formula for perpendicular distance : | ax1 + by1 + c| / sqrt(a^2 + b^2)
# a = y2 - y1, b = x2 - x1, c = x2y1 - x1y2
# where (x1, y1) and (x2, y2) are the two points between which the line is drawn
dist = []

for i in range(len(p0)):
    dist.append(calcDist(p0[i], p1[i], pt))
dist

[7.602631123499284, 12.020815280171309, 9.470462247029646]

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
pt = [[12,13], [3,9], [7,11]]
dist = []

for i in range(len(p0)):
    dist.append(calcDist(p0[i], p1[i], pt[i]))
dist

[16.54690303349844, 12.020815280171309, 13.92715036327889]

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
arr = np.arange(1, 10).reshape(3, 3)
subPartDimension = (2, 3)
startPos = (1, 1)
res = []

for i in range(startPos[0], startPos[0] + subPartDimension[0]):
    subArr=[]
    for j in range(startPos[1], startPos[1] + subPartDimension[1]):
        if ((i >= len(arr)) or j >= (len(arr[0]))):
            subArr.append(0)
        else:
            subArr.append(arr[i][j])
    res.append(subArr)
res

[[5, 6, 0], [8, 9, 0]]