# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [3]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np
import math

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)

1.24.3


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
v1 = np.zeros(10)
print(v1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [7]:
print(v1.size)
print(v1.nbytes)

10
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
v1 = np.zeros(10)
v1[4] = 1
print(v1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
v1 = np.arange(10, 50)
print(v1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
for i in range(int(len(v1) / 2)):
    tmp = v1[i]
    v1[i] = v1[len(v1) - 1 - i]
    v1[len(v1) - 1 - i] = tmp
print(v1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
mat1 = np.arange(0, 9).reshape(3, 3)
print(mat1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
v1 = np.array([1,2,0,0,4,0])
res=[]
for i in range(len(v1)):
    if v1[i] == 0:
        res.append(i)
print(res)

[2, 3, 5]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
id1 = np.eye(3)
print(id1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
v2 = np.random.randn(27).reshape(3, 3, 3)
print(v2)

[[[ 0.20437166  1.27433687  0.60423838]
  [ 0.37378903 -2.10895267 -0.05108117]
  [-1.02301133  1.55973632 -0.05069938]]

 [[-1.5856936  -0.90512048  1.48382157]
  [-1.27978134  1.53386121 -0.59167575]
  [-0.6989597  -0.49987877 -1.23799825]]

 [[-0.51190364 -0.62888122 -0.38191208]
  [ 1.13805774  0.11445629  0.25738408]
  [-0.24983392 -0.99867775 -1.05295352]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
v1 = np.random.rand(100).reshape(10, 10)
maxNum = v1.max()
minNum = v1.min()
print("[+] MaxNum: ", maxNum, " MinNum: ", minNum)

[+] MaxNum:  0.9956786522901505  MinNum:  0.0016086506971596526


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
meanVal = np.random.rand(30).mean()
print(meanVal)

0.4151738444219063


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
mat1 = np.arange(0, 25).reshape(5, 5)
l1, l2 = 0, len(mat1[0]) - 1
w1, w2 = 0, len(mat1) - 1


for l in range(l1, l2 + 1):
    mat1[w1][l] = 1
for w in range(w1, w2 + 1):
    mat1[w][l2] = 1
for l in range(l2, l1 - 1, -1):
    mat1[w2][l] = 1
for w in range(w2, w1 - 1, -1):
    mat1[w][l1] = 1

print(mat1)

[[ 1  1  1  1  1]
 [ 1  6  7  8  1]
 [ 1 11 12 13  1]
 [ 1 16 17 18  1]
 [ 1  1  1  1  1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
mat1 = np.arange(1, 10).reshape(3, 3)
print(mat1, end='\n\n')

mat1 = np.pad(mat1, ((2, 3), (1, 0)), mode='constant', constant_values= 0)
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0 0 0 0]
 [0 0 0 0]
 [0 1 2 3]
 [0 4 5 6]
 [0 7 8 9]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [20]:
v1 = np.nan
print(type(v1))
print(type(np.nan))

# NaN (Not a Number) represents an undefined or unrepresentable value in floating-point arithmetic.
# It's not equal to any other value, including itself.

# The == operator performs value comparison.
# NaN (Not a Number) is defined as not equal to any v

# The "is" operator performs identity comparison.
# It checks if two objects refer to the exact same memory location.

# In many Python implementations, np.nan is often a singleton object, 
# meaning there's only one instance of it in memory.

if v1 == v1:
    print("Yes")

if np.nan == np.nan:
    print("Yes")

if np.nan is np.nan:
    print("Yes")

if np.isnan(v1):
    print("Yes")


<class 'float'>
<class 'float'>
Yes
Yes


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [21]:
mat1 = np.zeros(25).reshape(5, 5)
count = 0

for i in range (len(mat1)):
    for j in range(len(mat1[0])):
        if (i > j):
            mat1[i][j] = count
            count += 1
print(mat1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 2. 0. 0. 0.]
 [3. 4. 5. 0. 0.]
 [6. 7. 8. 9. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
mat1 = np.zeros(64).reshape(8, 8)
count = 1

for i in range(len(mat1)):
    if (count % 2 == 0):
        count = 1
    else:
        count = 0
    for j in range(len(mat1[0])):
        if (count % 2 == 0):
            mat1[i][j] = 0
        else:
            mat1[i][j] = 1
        count += 1

print(mat1)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [23]:
# index would be (1,5,3)
v2 = np.arange(11, 347).reshape(6, 7, 8)
print(v2[1][5][3])

# Using unravel_index
flatIndx = 99 #(c-style indexing so 100th element is at flat_index:99)
idx = np.unravel_index(flatIndx, (6, 7, 8))
print(idx)

110
(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [24]:
v1 = np.arange(1, 5).reshape(2, 2)
print(v1, end='\n\n')

v1 = np.tile(v1, ((3, 1))) # 3 times niche and 1 time side mei
print(v1)

[[1 2]
 [3 4]]

[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [25]:
if np.sqrt(-1) == np.emath.sqrt(-1): # nan != j
    print("Yes")
else:
    print("No")

No


/var/folders/2v/33p_wnzd3gj0lfp0r82qrhl00000gp/T/ipykernel_5561/1652928068.py:1: RuntimeWarning: invalid value encountered in sqrt
  if np.sqrt(-1) == np.emath.sqrt(-1): # nan != j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [26]:
yesterday = np.datetime64('today') - np.timedelta64(1,'D')
today = np.datetime64('today')
tomorrow = np.datetime64('today') - np.timedelta64(1, 'D')
yesterday

numpy.datetime64('2024-02-05')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [27]:
startDate = np.datetime64('2016-07-01')
endDate = np.datetime64('2016-08-01')
np.arange(startDate, endDate, dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [28]:
a = np.ones(3)
b = np.ones(3)
((a + b) * (-a/2))

array([-1., -1., -1.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [29]:
arr = np.random.uniform(low=0, high=100, size=10)
print(arr)

a1 = np.floor(arr)
a2 = arr.astype(int)

print(a1)
print(a2)

[13.48472873 61.80678124 64.26415555 83.05215561 94.4300972  55.31424167
 39.86640565 71.09122879 91.72034896 47.61098821]
[13. 61. 64. 83. 94. 55. 39. 71. 91. 47.]
[13 61 64 83 94 55 39 71 91 47]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [30]:
arr = np.zeros((5, 5))
addArr = np.arange(5)
arr + addArr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [31]:
np.random.randint(low=0, high=10, size=10)

array([6, 5, 5, 6, 5, 6, 3, 5, 5, 6])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

np.linspace(0, 1, 11)[1:]

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [32]:
arr = np.sort(np.random.rand(10))
arr

array([0.10577261, 0.29764885, 0.30542913, 0.32228657, 0.41121976,
       0.45412424, 0.50068288, 0.85683837, 0.8786029 , 0.88166813])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [33]:
np.add.reduce(arr)

5.014273436222765

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [34]:
a = np.random.rand(5)
b = np.random.rand(5)

np.array_equal(a, b)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [35]:
# true immutability isn't directly achievable like it is with Python strings or tuples. However, you
# can employ several techniques to effectively restrict or prevent modifications and achieve a state
# close to immutability

arr = np.arange(5)
arr.flags.writeable = False

try:
    arr[0] = 1
except ValueError:
    print("Array is read-only")

Array is read-only


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [36]:
arr = np.arange(1, 6)
new_arr = np.array([])

for i in range(len(arr)):
    new_arr= np.concatenate((new_arr[:4 * i], [0,0,0,i + 1], new_arr[4 * i:]))
    print(new_arr)

[0. 0. 0. 1.]
[0. 0. 0. 1. 0. 0. 0. 2.]
[0. 0. 0. 1. 0. 0. 0. 2. 0. 0. 0. 3.]
[0. 0. 0. 1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4.]
[0. 0. 0. 1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [37]:
arr1 = np.random.rand(75).reshape(5, 5, 3)
arr2 = np.arange(25).reshape(5, 5, 1)

arr1 * arr2 # element-wise multiplication

array([[[ 0.        ,  0.        ,  0.        ],
        [ 0.49533042,  0.79254207,  0.10201936],
        [ 0.02365016,  1.47465772,  1.43805149],
        [ 1.26462454,  2.8077074 ,  1.81174856],
        [ 2.97840909,  1.01474261,  2.80906749]],

       [[ 0.49515066,  2.37419798,  1.03577398],
        [ 0.89278746,  3.04892193,  1.80330556],
        [ 0.51653033,  5.25392919,  2.82144918],
        [ 5.07829474,  1.25046716,  7.24471451],
        [ 5.43724965,  8.05151863,  1.88189866]],

       [[ 4.80764071,  9.38333378,  3.59382364],
        [ 1.57294295,  8.25578886,  5.21375052],
        [10.46331955, 10.30208623,  3.40180024],
        [11.21579662, 10.9310907 , 10.21982682],
        [ 4.47694762,  0.13316595,  4.62521642]],

       [[ 8.05726547,  3.81348892,  0.22453405],
        [15.15914323,  4.93775847,  0.17284037],
        [12.74396669,  2.39902831, 11.4531084 ],
        [15.82704051,  7.83038853,  2.82181764],
        [12.19010746, 17.43831243,  3.13858335]],

       [[ 5.

#### 72. How to swap two rows of an array? (★★★)

In [38]:
arr = np.arange(9).reshape(3, 3)
tmp = arr[0].copy()
arr[0] = arr[1]
arr[1] = tmp
arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [39]:
c = [1,3,4,4]
a = []

for i in range(len(c)):
    for j in range(c[i]):
        a.append(i)
a

[0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [40]:
window_size = 3
arr = [1,3,4,5,7,11,13,12,12]
movingAvg = []

for i in range(len(arr) - window_size + 1):
    sum = 0
    for j in range(i, i + window_size):
        sum += arr[j]
    movingAvg.append(sum / window_size)
movingAvg

[2.6666666666666665,
 4.0,
 5.333333333333333,
 7.666666666666667,
 10.333333333333334,
 12.0,
 12.333333333333334]

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [41]:
z = [1,2,3,4,5,6,7,8,9]
arr = []

for i in range(0, len(z) - 3 + 1, 3):
    arr.append([z[i], z[i + 1], z[i + 2]])
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [42]:
boolVar = True
boolVar = not boolVar

floatVal = 5.04
floatVal *= -1

print("[+] Boolean: ", boolVar, " floatVal: ", floatVal)

[+] Boolean:  False  floatVal:  -5.04


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [43]:
def calcDist(l1, l2, pt):
    a = l2[1] - l1[1]
    b = l2[0] - l1[0]
    c = l2[0] * l1[1] - l1[0] * l2[1]

    dist = abs(a * pt[0] + b * pt[1] + c) / math.sqrt(a**2 + b**2)
    return dist

In [44]:
p0 = [[0,0], [5,10], [2,2]]
p1 = [[1,2], [8,13], [7,4]]
pt = [5, 7]

# Formula for perpendicular distance : | ax1 + by1 + c| / sqrt(a^2 + b^2)
# a = y2 - y1, b = x2 - x1, c = x2y1 - x1y2
# where (x1, y1) and (x2, y2) are the two points between which the line is drawn
dist = []

for i in range(len(p0)):
    dist.append(calcDist(p0[i], p1[i], pt))
dist

[7.602631123499284, 12.020815280171309, 9.470462247029646]

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [45]:
pt = [[12,13], [3,9], [7,11]]
dist = []

for i in range(len(p0)):
    dist.append(calcDist(p0[i], p1[i], pt[i]))
dist

[16.54690303349844, 12.020815280171309, 13.92715036327889]

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [46]:
arr = np.arange(1, 10).reshape(3, 3)
subPartDimension = (2, 3)
startPos = (1, 1)
res = []

for i in range(startPos[0], startPos[0] + subPartDimension[0]):
    subArr=[]
    for j in range(startPos[1], startPos[1] + subPartDimension[1]):
        if ((i >= len(arr)) or j >= (len(arr[0]))):
            subArr.append(0)
        else:
            subArr.append(arr[i][j])
    res.append(subArr)
res

[[5, 6, 0], [8, 9, 0]]